
name: ars_dolar
description: App for calculating amount of transfer money with commission.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  intl: ^0.18.0
  http: ^1.1.0
  url_launcher: ^6.1.11
  adaptive_theme: ^3.2.1
  json_annotation: ^4.8.1
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/dollar.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/dollar.png"
  # image_path: "assets/ios.png"
  # image_path_android: "assets/logo.png"
  # adaptive_icon_background: "#000000"
  # adaptive_icon_foreground: "assets/logo.png"
  remove_alpha_ios: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
flutter_intl:
  enabled: true

# name: ars_dolar
# description: A new Flutter project.
# publish_to: 'none'
# version: 0.1.0

# environment:
#   sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0

# flutter:
#   uses-material-design: true
